### ISSUE TITLE
wrong data with AirPods Pro

### ISSUE THREAD

**Issue by godbout** [BeneathCloud/AirpodsBattery#1]
not sure whether it's just with the AirPods Pro, but the left shows the right battery level, and the right is empty.

for line 31 (https://github.com/BeneathCloud/AirpodsBattery/blob/62e56ad3da5ef6b8ee2c26d12b62412cdbeef208/AirpodsBattery#L31), variables need to be changed to $5 and $7 respectively, at least under the latest version of Catalina.

great workflow, thanks!

**Comment by guiyuanju** [comment]
Thank you very much!
I don't have a pair of Airpods Pro, it works for my Airpods all the time (Mac os Catalina 10.15.4).
And now I have modified the code, it should work with Airpods Pro now.


> not sure whether it's just with the AirPods Pro, but the left shows the right battery level, and the right is empty.
> 
> for line 31 (
> 
> https://github.com/BeneathCloud/AirpodsBattery/blob/62e56ad3da5ef6b8ee2c26d12b62412cdbeef208/AirpodsBattery#L31
> 
> ), variables need to be changed to $5 and $7 respectively, at least under the latest version of Catalina.
> great workflow, thanks!

**Comment by godbout** [comment]
hey @BeneathCloud. thanks!
actually i ended up doing a fork and making the changes :https://github.com/godbout/AirpodsBattery
