### ISSUE TITLE
Show incorrect information on m1 mac

### ISSUE THREAD

**Issue by KeqiZeng** [BeneathCloud/AirpodsBattery#3]
Hi, I have downloaded the latest release and tried. Now, I get "L:  R:  R:  ". Here is some informations from alfred:
```
[16:16:23.267] Logging Started...
[16:16:26.244] Airpods Battery[Script Filter] Queuing argument '(null)'
[16:16:26.549] Airpods Battery[Script Filter] Script with argv '(null)' finished
[16:16:26.552] Airpods Battery[Script Filter] {"items": [
    {
        "uid": "battery",
        "title": "L: R: R: ",
        "subtitle": "Press Enter to disconnect",
        "arg": "1",
    }
]}
```

**Comment by guiyuanju** [comment]
That's strange, I'm using M1 macbook air (Big Sur) too, and it works fine.
Is your macbook connecting to multiple earphones?

Can you try to execute the bash script below and see what is the output?
```bash
#!/usr/bin/env bash

OUTPUT='';
BLUETOOTH_DEFAULTS=$(defaults read /Library/Preferences/com.apple.Bluetooth);
SYSTEM_PROFILER=$(system_profiler SPBluetoothDataType 2>/dev/null)
MAC_ADDR=$(grep -b2 "Minor Type: Headphones"<<<"${SYSTEM_PROFILER}"|awk '/Address/{print $3}')
CONNECTED=$(grep -ia6 "${MAC_ADDR}"<<<"${SYSTEM_PROFILER}"|awk '/Connected: Yes/{print 1}')
BLUETOOTH_DATA=$(grep -ia6 '"'"${MAC_ADDR}"'"'<<<"${BLUETOOTH_DEFAULTS}")
BATTERY_LEVELS=("BatteryPercentLeft" "BatteryPercentRight")

if [[ "${CONNECTED}" ]]; then
    for I in "${BATTERY_LEVELS[@]}"; do
        declare -x "${I}"="$(awk -v pat="${I}" '$0~pat{gsub (";",""); print $3 }'<<<"${BLUETOOTH_DATA}")"
        [[ ! -z "${!I}" ]] && OUTPUT="${OUTPUT} $(awk '/BatteryPercent/{print substr($0,15,1)": "}'<<<"${I}")${!I}%"
    done

    battery=$(echo $OUTPUT | awk '{
        l = "";
        r = "";
        for (i = 1; i < NF; i++) {
          if ($i == "L:") {l = $(i + 2);}
          else if ($i == "R:") {r = $(i + 2);}
        } 
        print "L: " l, "R: " r
      }')
    arg=1;
    subtitle="Press Enter to disconnect";
else
    battery="Not Connected"
    arg=0;
    subtitle="Press Enter to connect";
fi

echo $OUTPUT
echo $battery
```

Here, the `$OUTPUT` is the related infomation grepped from system, actually, the script of this part was grabbed from another repo, and I don't quite understand what it is doing ;D,  the only part I wrote is the awk code:
```bash
    battery=$(echo $OUTPUT | awk '{
        l = "";
        r = "";
        for (i = 1; i < NF; i++) {
          if ($i == "L:") {l = $(i + 2);}
          else if ($i == "R:") {r = $(i + 2);}
        } 
        print "L: " l, "R: " r
      }')
```
which filters the result of `$OUTPUT`, format it, and pass it to Alfred.
Since I cannot reproduce your problem in my computer, it is rather difficult for me to debug,
I will be really appreciated if you could try fixing it.

Hint:
Depending on what the content of the `$OUTPUT` is, you should try to modify the awk code to filter and format it correctly.

**Comment by KeqiZeng** [comment]
There is just an earphone connecting to my mac. I have tried the bash script in my terminal and I got this output
```
awk: syntax error at source line 1
 context is
	/BatteryPercent/{print >>>  substr($, <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
awk: syntax error at source line 1
 context is
	/BatteryPercent/{print >>>  substr($, <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
81% 76%
L: R:
```
It seems like `l` and `r` have no value.

Actually I have not learned awk. So it's also a little difficult for me to debug. I'm sorry for that. However, I have tried the fork of this repo in #1. It can work well on my mac. 

I think it's just a tool. If it can work for us, this is enough. We don't need to pursue perfection. Anyway, thanks again bro, I find solution here. Have a good day!

**Comment by guiyuanju** [comment]
Good to here that, thank you~
